Ext.define('Onlineshopping.onlineshopping.shared.shop.model.retailcontext.retail.PaymentDetailsModel.PaymentDetailsModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "amount",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "ccHolderName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "creditCardNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "customerId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "cvvNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "expiryMonth",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "expiryYear",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "refId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userId",
          "type": "string",
          "defaultValue": ""
     }]
});