Ext.define('Onlineshopping.onlineshopping.shared.shop.model.retailcontext.retail.CartPartialModel.CartPartialModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "itemId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "product",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "brand",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "category",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "item",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemIcon",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "quantity",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemPrice",
          "type": "int",
          "defaultValue": ""
     }]
});